Add foundational gun system
ageuxo/glorious-gunpowder pull request #5
Opened 2024-05-20 17:20 UTC by TheDrOfDoctoring

`AbstractFirearm` handles the majority of logic for guns, including making use of the attribute system. All gun attributes are currently taken into account. Temporarily a `BasicFirearm` has been included as well as a default set of attributes for testing purposes. 
Bullets are added without a recipe for now and rendered.
Note block sound effects are currently used as placeholders for reloading sounds.

2024-05-21 22:02 UTC, ageuxo requested changes
Just a few small things, otherwise looking very good!

2024-05-21 22:02 UTC, ageuxo commented on src/main/java/io/github/ageuxo/gloriousgunpowder/client/render/ClientEventHandler.java
> +public class ClientEventHandler {
Maybe move this up one level to the client package, or we could make another client event handler there, and rename this one to RenderHandler or the like, I'll leave the choice up to you ;)

2024-05-21 22:02 UTC, ageuxo commented on src/main/java/io/github/ageuxo/gloriousgunpowder/data/GunAttribute.java
>              instance.group(
Is this really the best way of storing the stats now that they're data defined? I don't know about the StreamCodec, but the regular Codec we could serialise it as a list of Objects mapping GunStat -> Value.
I could probably take a look at that doing that if you'd like.

2024-05-21 22:02 UTC, ageuxo commented on src/main/resources/assets/glorious_gunpowder/sounds/cc/LICENSE.TXT
> +The sounds in this directoy are available under different Creative Commons Licenses.
directory*

2024-05-23 10:42 UTC, TheDrOfDoctoring commented on src/main/java/io/github/ageuxo/gloriousgunpowder/data/GunAttribute.java
>              instance.group(
implemented temporary rework to make use of gunstats, may require future  changes

2024-05-23 10:46 UTC, ageuxo approved these changes
LGTM 👍

2024-05-23 10:48 UTC, merged